@Test public void testCreateNumber() throws Exception { assertEquals(Integer.valueOf(0), NumberUtils.createNumber("0")); assertEquals(Integer.valueOf(1), NumberUtils.createNumber("1")); assertEquals(Integer.valueOf(2), NumberUtils.createNumber("2")); assertEquals(Integer.valueOf(3), NumberUtils.createNumber("3")); assertEquals(Integer.valueOf(4), NumberUtils.createNumber("4")); assertEquals(Integer.valueOf(5), NumberUtils.createNumber("5")); assertEquals(Integer.valueOf(6), NumberUtils.createNumber("6")); assertEquals(Integer.valueOf(-1), NumberUtils.createNumber("-1")); }